wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720687985
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 98
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 98
      - 105
      3:
      - 13
      - 23
      - 61
      4: 3.10.12
      5: 0.17.4
      6: 4.40.1
      8:
      - 5
      13: linux-x86_64
